### PR TITLE
Fix user URL detection, reduce chance of rate limiting

### PR DESCRIPTION
**Pull request by moralrecordings**
Patch returns the extension to a mostly-working state.

### CODE REVIEW

**Comment by Sacred-Shadow** [comment]
@dmstern wie schaut es aus? Is der Fix okay?

**Comment by dmstern** [comment]
Hey @moralrecordings,

thank you very much for your contribution! It works fine and I'm glad to merge it to master. Unfortunately, I had to fix another bug first and then messed up a bit with my branches.

But I wanted to ensure your contribution gets to the git log, so I forked your branch to my repo, rebased it to master and merged it, see #66.

I'll close this, but your commits have been applied. :)

**Comment by moralrecordings** [comment]
Thanks! This is a really valuable tool, thanks for creating it. 

One thing I did notice was that on the Likes page on a tweet, Twitter will let you scroll for a _very_ long time for the first request, but subsequent requests will only show you what  you've seen + new likes. So for non-explosive tweets the list comes up empty after the first round of blocking. As the number of accounts per round is limited by the number of names crammable into a GET querystring, would it be possible to ship a bigger list directly to a POST API on Heroku? I figured I should ask first before prototyping it.

**Comment by dmstern** [comment]
Yes, this is technically possible, we tried this in the first run but then decided to use the GET request via the link that opens in new browser tab because it was easier to implement and improved the usability (in our oppinion ;)).

But instead of switching to a POST request here, I think it would be more feasible to get rid of this whole UI-scraping-and -redirecting-to-another-(heroku)-website by using the new Twitter API [`/likes`](https://developer.twitter.com/en/docs/twitter-api/tweets/likes/introduction) endpoint to get the likes and then post the list to the [`/blocks`](https://developer.twitter.com/en/docs/twitter-api/v1/accounts-and-users/mute-block-report-users/api-reference/post-blocks-create) endpoint.

I am only scruggling a bit with the authentication. If you want to support here, you're welcome. :)

**Comment by dmstern** [comment]
@moralrecordings I think I have to correct myself: since the Twitter UI seems to show way more users in the likers list by scrolling down in large likes-lists than the limit of the `likes` API endpoint (currently `100`), the scraping approach still seems to bring a huge benefit.
A few month ago, the amount of users that could be seen in the likes-list from the UI was limited to only 80.
Since we can get hundreds of users from the UI (I didn't really recognize this LOL), your suggestion to use a POST endpoint of our own service seems still feasible.

Maybe we should shift this conversation to new issue... ;)

**Pull request closed without merging**
